### ISSUE TITLE
Change controlls

### ISSUE THREAD

**Issue by jasonTelanoff** [TeddyTelanoff/MultiPlatform#45]
Falling is not intuitive. Change it to double pressing "s".

**Comment by Treidexy** [comment]
I'd say, yes, add double 's', but still keep the old method.

**Comment by jasonTelanoff** [comment]
Cool, that's the plan then

**Comment by jasonTelanoff** [comment]
double crouching now drops you, frames needs to be decreased.

**Comment by jasonTelanoff** [comment]
nvm

**Comment by jasonTelanoff** [comment]
fixed
